### PR TITLE
Adds buffering for incoming range messages

### PR DESCRIPTION
**Pull request by AlexReimann**
Already upstream for quite some time:
https://github.com/DLu/navigation_layers/pull/18

Compiles and did a simple running test, seems to work.

### CODE REVIEW

**Comment by AlexReimann** [comment]
@bit-pirate

**Comment by AlexReimann** [comment]
And maybe give me access rights to this repo :>

**Comment by bit-pirate** [comment]
Added you to the repo.

**Comment by bit-pirate** [comment]
But holding this off until after our next stable release.

**Pull request merged**
